trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE
    - README.md
    - SECURITY.md
pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE
    - README.md
    - SECURITY.md

resources:
- repo: self

variables:
  containerRegistry: 'joshcacr.azurecr.io'
  setupBatchkit: 'setup_batchkit.py'
  setupBatchkit2: setup_batchkit.py
  setupExamples: 'setup_examples.py'
  setupExamples2: "setup_examples"
  vmImageName: 'ubuntu-20.04'
  imageName: 'batchkit/speech-batch-kit'
  # imageName: 'joshcacr.azurecr.io/speech-batch-kit'

stages:
- stage: BuildTestRelease 
  displayName: Build, Test, and Release Python packages and Docker image in single stage
  jobs:   
  - job: BuildTestRelease
    displayName: Build, Test, and Release Python packages and Docker image in single job
    pool:
      vmImage: $(vmImageName)
    steps:

# BUILD AND TEST PIPELINE TASKS
    - task: CmdLine@2
      displayName: Setup Python virtual environment and install required packages Python package
      inputs:
        script: |
          sudo apt-get install dos2unix
          sudo apt-get install -y python3-venv
          sudo apt install python-is-python3
          python -m venv my_venv
          source my_venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install twine wheel yolk3k
    # - task: CmdLine@2
    #   displayName: Build Python package
    #   inputs:
    #     script: |
    #       source my_venv/bin/activate
    #       chmod 755 ci/parse_package_versions $(setupBatchkit) $(setupExamples) $(setupBatchkit2)
    #       dos2unix ci/parse_package_versions ci/build_packages
    #       echo "Verifying Python package versions updated"
    #       ./ci/parse_package_versions
    #       echo "Building Python packages"
    #       . ci/build_packages
    #       echo $BATCHKIT_EXAMPLES_PKG
    - task: CmdLine@2
      displayName: Build Python package AGAIN
      inputs:
        script: |
          source my_venv/bin/activate
          chmod 755 ci/parse_package_versions $(setupBatchkit) $(setupExamples) $(setupBatchkit2)
          dos2unix ci/parse_package_versions ci/build_packages
          echo "Verifying Python package versions updated"
          ./ci/parse_package_versions
          echo "Building Python packages"
          python $(setupBatchkit) sdist bdist_wheel
          python $(setupExamples) sdist bdist_wheel
          echo $BATCHKIT_EXAMPLES_PKG
          ls -a
          ls dist -a
    # - task: CmdLine@2
    #   displayName: Execute batchkit Python package unit and stress tests
    #   condition: always()
    #   inputs:
    #     script: |
    #       source my_venv/bin/activate
    #       echo $BATCHKIT_EXAMPLES_PKG
    #       chmod 755 run-stress-tests.py run-tests
    #       dos2unix run-tests
    #       echo "Executing unit tests"
    #       ./run-tests
    #       echo "Executing stress tests"
    #       python run-stress-tests.py
    #       ls -a
    #       ls dist -a
    - task: Docker@2
      displayName: Build Docker image
      condition: always()
      inputs:
        command: build
        repository: $(imageName)
        Dockerfile: batchkit_examples/speech_sdk/Dockerfile
        containerRegistry: $(dockerRegistryServiceConnection)
        buildContext: $(Build.Repository.LocalPath)
        tags: |
          test
          latest
        # arguments: --build-arg BATCHKIT_EXAMPLES_PKG='batchkit_examples_speechsdk'
    - task: CmdLine@2
      displayName: Print current contents
      condition: always()
      inputs:
        script: |
          source my_venv/bin/activate
          ls -a
          docker images
          docker ps -a

# need to add container registry to tag path: containerRegistry: 'joshcacr.azurecr.io'
    - task: CmdLine@2
      displayName: Execute Speech Batch Kit sanity test
      inputs:
        script: |
          source my_venv/bin/activate
          chmod 755 ci/speech_batch_kit_sanity_test
          dos2unix ci/speech_batch_kit_sanity_test
          pushd ci
          ./speech_batch_kit_sanity_test
          popd

# RELEASE PIPELINE TASKS
    # - task: CmdLine@2
    #   displayName: Publish Python packages
    #   condition: eq(variables['Build.Reason'], 'PullRequest')

    #   # use env to map secret variables to an env variable with bash and Powershell scripts
    #   env: 
    #     PYPI_API_TOKEN: $(PYPI_API_TOKEN)
    #   inputs:
    #     script: |
    #       source my_venv/bin/activate
    #       python -m pip install --upgrade pip
    #       twine check dist/*
    #       twine upload dist/* -u __token__ -p $PYPI_API_TOKEN
    - task: Docker@2
      displayName: Push Docker image
      # condition: eq(variables['Build.Reason'], 'PullRequest')
      # secret variables must be called with $() notation outside of bash and Powershell script tasks
      inputs:
        command: push
        repository: $(imageName)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          test
    - task: Docker@2
      displayName: Push Docker image
      condition: always()
      # condition: eq(variables['Build.Reason'], 'PullRequest')
      # secret variables must be called with $() notation outside of bash and Powershell script tasks
      inputs:
        command: push
        repository: $(imageName)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest